# Generated by Django 2.2 on 2019-12-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='mainApp.Tags'),
        ),
    ]
