# Generated by Django 2.2 on 2019-12-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_posts_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(),
        ),
    ]
