# Generated by Django 2.2 on 2019-12-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20191223_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ttt_k',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttttt', models.CharField(max_length=50, verbose_name='мой тест')),
            ],
        ),
        migrations.CreateModel(
            name='MyTesst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttttt', models.CharField(max_length=50, verbose_name='мой тест')),
                ('body', models.TextField(blank=True, db_index=True, verbose_name='уууыыы')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='ууqqq')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Ttt_k')),
            ],
        ),
    ]
